export const SINGUP_USER ="SINGUP_USER"
export const SINGIN_USER ="SINGIN_USER"
export const FORGOT_PASSWORD ="FORGOT_PASSWORD"
export const SIGNEDIN_USER ="SIGNEDIN_USER"
export const SIGNOUT_USER ="SIGNOUT_USER"
export const SIGNEDOUT_USER ="SIGNEDOUT_USER"
export const GOOGLE_SIGN_USER ="GOOGLE_SIGN_USER"

export const SET_ALERT = "SET_ALERT";
export const RESET_ALERT = "RESET_ALERT";
